version: "3.7"

services:
  client:
    container_name: client
    image: node:14.17-alpine
    depends_on:
      - api
      - mongodb
    command: >
      sh -c "yarn &&
          yarn start"
    ports:
      - 3000:3000
    working_dir: /app/client
    volumes:
      - ../client/:/app/client

  api:
    container_name: api
    image: node:14.17-alpine
    depends_on:
      - mongodb
    command: >
      sh -c "yarn &&
          yarn start:dev"
    ports:
      - 5000:5000
    working_dir: /app/server
    volumes:
      - ../server/:/app/server

  mongodb:
    container_name: database
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
